Bump API level for all example apps to 29
leetvr/hotham pull request #353
Opened 2022-09-16 21:11 UTC by MultisampledNight

Closes #228.

Completely untested running on a real device. The apk build was successful, but that probably means nothing.

2022-09-20 03:01 UTC, kanerogers requested changes
Looks good on device! Just needs to have the `ndk-glue` dependency changed back. :)

2022-09-20 10:46 UTC, MultisampledNight commented
`ndk-glue` downgraded, I'll rebase from main.

2022-09-23 07:23 UTC, kanerogers approved these changes
LGTM! 🦖

2022-09-23 07:23 UTC, kanerogers commented on examples/crab-saber/Cargo.toml
> +target_sdk_version = 29
Perfect! 🎉

2022-09-23 07:23 UTC, merged