Add custom rendering example
leetvr/hotham pull request #400
Opened 2022-10-26 20:51 UTC by rasmusgo

This is a rebased and cleaned up version of #389.

2022-10-27 00:05 UTC, kanerogers requested changes
Overall, this looks really good! As an aside, you could experiment with hardware ray tracing here if your target is PCVR. You could definitely have a hardware optimised fast path for devices that support it, then on mobile do everything in software - you might be interested in some of arm's [ray tracing work](https://www.youtube.com/watch?v=47HxKPPHyeU).

My only concern here is the refactoring of the fragment shaders; getting some of these functions to take parameters instead of just reading from registers makes sense from a code re-use point of view, but if you're making changes to the fragment shader just to support more modular shaders, I'd like to just be _absolutely sure_ that there's no performance regressions here.

Are you able to please run the stress tests on a Quest 2 and just make sure we haven't lost any performance from this? If it's an improvement or no change - all good! But if there is a performance regression, then I'd much rather you just copy-pasta from Hotham's shaders 😄

2022-10-27 00:06 UTC, kanerogers commented on hotham/src/systems/rendering.rs
> +                primitive_id: primitive.index_buffer_offset,
Good change, I like this 👍🏻

2022-10-27 05:18 UTC, rasmusgo commented on examples/custom-rendering/src/custom_render_context.rs
> +// TODO: Ensure that this index doesn't collide with hotham engine internals.
It does not! 😄 This used to be `6` and was inside the regular descriptor set but it has its own descriptor set now.

2022-10-27 21:02 UTC, rasmusgo commented
There was a performance regression uncovered by the benchmark so I reverted the changes tp `pbr.frag` which resolved it. I will try to reduce the duplication later on but this works for now.

2022-10-30 22:58 UTC, kanerogers approved these changes
This is good stuff!

I am a little nervous about making more of the renderer public, but I suppose it's a reasonable stop gap before exposing a cleaner custom rendering API. 

Approved! 🎉

2022-10-30 22:58 UTC, merged